# Use the official Node.js image as base image
FROM node:22.9.0

# Set the working directory
WORKDIR /app

# Expose port 80
EXPOSE 80

# Run the development server
CMD ["npm", "run", "dev", "--", "--host"]